### ISSUE TITLE
Web interface

### ISSUE THREAD

**Issue by deanpcmad** [spider-network/hetzner#9]
Do you recommend any web interfaces that will work along side this script, or works good with KVM?

**Comment by spider-network** [comment]
I never searched for a administration gui. personal i use my thor tasks e.g. `thor hetzner:vm:stop --name=vm-001` to manage the VMs, but i think it is possible to build a web gui on to of it.

What feature set do you expect from an web gui?

**Comment by deanpcmad** [comment]
I'm now using [Cloudmin](http://www.webmin.com/cloudmin.html). Nice little web interface for KVM, Xen and OpenVZ :)

**Comment by spider-network** [comment]
Thank for the link. I'll be looking at the tool and maybe integrated in the setup process. Are you satisfied with the tool?

**Comment by deanpcmad** [comment]
With your tools? Yeah, just I wanted an easier way to see the status of my VMs and also easily create them.

## 

Dean Perry
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)
